# Contenedor para GitLab versión Comunitaria - open source
version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-ce
    restart: unless-stopped
    hostname: 'gitlab.local'
    ports:
      - '80:80'       # HTTP access
      - '443:443'     # HTTPS access
      - '22:22'       # SSH access for Git
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local'
        # Para habilitar HTTPS, descomenta y ajusta certificados:
        # nginx['redirect_http_to_https'] = true
        # nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.crt"
        # nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.key"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
